name: deploy

on:
  push:
    branches:
      - master

jobs:
  gcp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@v2
        with:
          name: koresuki-nsfw-support
          runtime: nodejs16
          entry_point: koresuki
          env_vars: >-
            SAFE_CHANNEL_WEBHOOK_URL=${{ secrets.SAFE_CHANNEL_WEBHOOK_URL }}
            ,SAFE_CHANNEL_ID=${{ secrets.SAFE_CHANNEL_ID }}
            ,NSFW_CHANNEL_WEBHOOK_URL=${{ secrets.NSFW_CHANNEL_WEBHOOK_URL }}
            ,NSFW_CHANNEL_ID=${{ secrets.NSFW_CHANNEL_ID }}
